import {TOKENS} from '../tokens';

import {TestCase} from './types';

export const OPERATOR_FIXTURES: TestCase[] = [
  {
    input: '+',
    expected: [
      {
        type: 'ENCODING',
        kind: 'ENCODING',
        value: 'utf-8',
        startPos: {line: 0, column: 0},
        endPos: {line: 0, column: 0},
        colOffset: 0,
        lineNo: 0,
      },
      {
        type: 'OP',
        kind: 'PLUS',
        value: '+',
        startPos: {line: 1, column: 1},
        endPos: {line: 1, column: 2},
        lineNo: 1,
        colOffset: 1,
      },
      {
        type: 'ENDMARKER',
        kind: 'ENDMARKER',
        value: TOKENS.ENDMARKER,
        startPos: {line: 1, column: 2},
        endPos: {line: 1, column: 2},
        lineNo: 1,
        colOffset: 2,
      },
    ],
  },
  {
    input: '-',
    expected: [
      {
        type: 'ENCODING',
        kind: 'ENCODING',
        value: 'utf-8',
        startPos: {line: 0, column: 0},
        endPos: {line: 0, column: 0},
        colOffset: 0,
        lineNo: 0,
      },
      {
        type: 'OP',
        kind: 'MINUS',
        value: '-',
        startPos: {line: 1, column: 1},
        endPos: {line: 1, column: 2},
        lineNo: 1,
        colOffset: 1,
      },
      {
        type: 'ENDMARKER',
        kind: 'ENDMARKER',
        value: TOKENS.ENDMARKER,
        startPos: {line: 1, column: 2},
        endPos: {line: 1, column: 2},
        lineNo: 1,
        colOffset: 2,
      },
    ],
  },
  {
    input: '1 + 1',
    expected: [
      {
        type: 'ENCODING',
        kind: 'ENCODING',
        value: 'utf-8',
        startPos: {line: 0, column: 0},
        endPos: {line: 0, column: 0},
        colOffset: 0,
        lineNo: 0,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '1',
        startPos: {line: 1, column: 1},
        endPos: {line: 1, column: 2},
        lineNo: 1,
        colOffset: 1,
      },
      {
        type: 'OP',
        kind: 'PLUS',
        value: '+',
        startPos: {line: 1, column: 3},
        endPos: {line: 1, column: 4},
        lineNo: 1,
        colOffset: 3,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '1',
        startPos: {line: 1, column: 5},
        endPos: {line: 1, column: 6},
        lineNo: 1,
        colOffset: 5,
      },
      {
        type: 'ENDMARKER',
        kind: 'ENDMARKER',
        value: TOKENS.ENDMARKER,
        startPos: {line: 1, column: 6},
        endPos: {line: 1, column: 6},
        lineNo: 1,
        colOffset: 6,
      },
    ],
  },
  {
    input: '3 - 2.5',
    expected: [
      {
        type: 'ENCODING',
        kind: 'ENCODING',
        value: 'utf-8',
        startPos: {line: 0, column: 0},
        endPos: {line: 0, column: 0},
        colOffset: 0,
        lineNo: 0,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '3',
        startPos: {line: 1, column: 1},
        endPos: {line: 1, column: 2},
        lineNo: 1,
        colOffset: 1,
      },
      {
        type: 'OP',
        kind: 'MINUS',
        value: '-',
        startPos: {line: 1, column: 3},
        endPos: {line: 1, column: 4},
        lineNo: 1,
        colOffset: 3,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '2.5',
        startPos: {line: 1, column: 5},
        endPos: {line: 1, column: 8},
        lineNo: 1,
        colOffset: 5,
      },
      {
        type: 'ENDMARKER',
        kind: 'ENDMARKER',
        value: TOKENS.ENDMARKER,
        startPos: {line: 1, column: 8},
        endPos: {line: 1, column: 8},
        lineNo: 1,
        colOffset: 8,
      },
    ],
  },
  {
    input: '10. + 6 + 12 - 4',
    expected: [
      {
        type: 'ENCODING',
        kind: 'ENCODING',
        value: 'utf-8',
        startPos: {line: 0, column: 0},
        endPos: {line: 0, column: 0},
        colOffset: 0,
        lineNo: 0,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '10.',
        startPos: {line: 1, column: 1},
        endPos: {line: 1, column: 4},
        lineNo: 1,
        colOffset: 1,
      },
      {
        type: 'OP',
        kind: 'PLUS',
        value: '+',
        startPos: {line: 1, column: 5},
        endPos: {line: 1, column: 6},
        lineNo: 1,
        colOffset: 5,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '6',
        startPos: {line: 1, column: 7},
        endPos: {line: 1, column: 8},
        lineNo: 1,
        colOffset: 7,
      },
      {
        type: 'OP',
        kind: 'PLUS',
        value: '+',
        startPos: {line: 1, column: 9},
        endPos: {line: 1, column: 10},
        lineNo: 1,
        colOffset: 9,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '12',
        startPos: {line: 1, column: 11},
        endPos: {line: 1, column: 13},
        lineNo: 1,
        colOffset: 11,
      },
      {
        type: 'OP',
        kind: 'MINUS',
        value: '-',
        startPos: {line: 1, column: 14},
        endPos: {line: 1, column: 15},
        lineNo: 1,
        colOffset: 14,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '4',
        startPos: {line: 1, column: 16},
        endPos: {line: 1, column: 17},
        lineNo: 1,
        colOffset: 16,
      },
      {
        type: 'ENDMARKER',
        kind: 'ENDMARKER',
        value: TOKENS.ENDMARKER,
        startPos: {line: 1, column: 17},
        endPos: {line: 1, column: 17},
        lineNo: 1,
        colOffset: 17,
      },
    ],
  },
  {
    input: '12   * -1000 /      6',
    expected: [
      {
        type: 'ENCODING',
        kind: 'ENCODING',
        value: 'utf-8',
        startPos: {line: 0, column: 0},
        endPos: {line: 0, column: 0},
        colOffset: 0,
        lineNo: 0,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '12',
        startPos: {line: 1, column: 1},
        endPos: {line: 1, column: 3},
        lineNo: 1,
        colOffset: 1,
      },
      {
        type: 'OP',
        kind: 'STAR',
        value: '*',
        startPos: {line: 1, column: 6},
        endPos: {line: 1, column: 7},
        lineNo: 1,
        colOffset: 6,
      },
      {
        type: 'OP',
        kind: 'MINUS',
        value: '-',
        startPos: {line: 1, column: 8},
        endPos: {line: 1, column: 9},
        lineNo: 1,
        colOffset: 8,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '1000',
        startPos: {line: 1, column: 9},
        endPos: {line: 1, column: 13},
        lineNo: 1,
        colOffset: 9,
      },
      {
        type: 'OP',
        kind: 'SLASH',
        value: '/',
        startPos: {line: 1, column: 14},
        endPos: {line: 1, column: 15},
        lineNo: 1,
        colOffset: 14,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '6',
        startPos: {line: 1, column: 21},
        endPos: {line: 1, column: 22},
        lineNo: 1,
        colOffset: 21,
      },
      {
        type: 'ENDMARKER',
        kind: 'ENDMARKER',
        value: TOKENS.ENDMARKER,
        startPos: {line: 1, column: 22},
        endPos: {line: 1, column: 22},
        lineNo: 1,
        colOffset: 22,
      },
    ],
  },
];
