import {TOKENS} from '../tokens';

import {TestCase} from './types';

export const OPERATOR_FIXTURES: TestCase[] = [
  {
    input: '+',
    expected: [
      {
        type: 'ENCODING',
        kind: 'ENCODING',
        value: 'utf-8',
        startPos: {line: 0, column: 0},
        endPos: {line: 0, column: 0},
        colOffset: 0,
        lineNo: 0,
      },
      {
        type: 'OP',
        kind: 'PLUS',
        value: '+',
        startPos: {line: 1, column: 1},
        endPos: {line: 1, column: 2},
        lineNo: 1,
        colOffset: 1,
      },
      {
        type: 'ENDMARKER',
        kind: 'ENDMARKER',
        value: TOKENS.ENDMARKER,
        startPos: {line: 1, column: 2},
        endPos: {line: 1, column: 2},
        lineNo: 1,
        colOffset: 2,
      },
    ],
  },
  {
    input: '-',
    expected: [
      {
        type: 'ENCODING',
        kind: 'ENCODING',
        value: 'utf-8',
        startPos: {line: 0, column: 0},
        endPos: {line: 0, column: 0},
        colOffset: 0,
        lineNo: 0,
      },
      {
        type: 'OP',
        kind: 'MINUS',
        value: '-',
        startPos: {line: 1, column: 1},
        endPos: {line: 1, column: 2},
        lineNo: 1,
        colOffset: 1,
      },
      {
        type: 'ENDMARKER',
        kind: 'ENDMARKER',
        value: TOKENS.ENDMARKER,
        startPos: {line: 1, column: 2},
        endPos: {line: 1, column: 2},
        lineNo: 1,
        colOffset: 2,
      },
    ],
  },
  {
    input: '1 + 1',
    expected: [
      {
        type: 'ENCODING',
        kind: 'ENCODING',
        value: 'utf-8',
        startPos: {line: 0, column: 0},
        endPos: {line: 0, column: 0},
        colOffset: 0,
        lineNo: 0,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '1',
        startPos: {line: 1, column: 1},
        endPos: {line: 1, column: 2},
        lineNo: 1,
        colOffset: 1,
      },
      {
        type: 'OP',
        kind: 'PLUS',
        value: '+',
        startPos: {line: 1, column: 3},
        endPos: {line: 1, column: 4},
        lineNo: 1,
        colOffset: 3,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '1',
        startPos: {line: 1, column: 5},
        endPos: {line: 1, column: 6},
        lineNo: 1,
        colOffset: 5,
      },
      {
        type: 'ENDMARKER',
        kind: 'ENDMARKER',
        value: TOKENS.ENDMARKER,
        startPos: {line: 1, column: 6},
        endPos: {line: 1, column: 6},
        lineNo: 1,
        colOffset: 6,
      },
    ],
  },
  {
    input: '3 - 2.5',
    expected: [
      {
        type: 'ENCODING',
        kind: 'ENCODING',
        value: 'utf-8',
        startPos: {line: 0, column: 0},
        endPos: {line: 0, column: 0},
        colOffset: 0,
        lineNo: 0,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '3',
        startPos: {line: 1, column: 1},
        endPos: {line: 1, column: 2},
        lineNo: 1,
        colOffset: 1,
      },
      {
        type: 'OP',
        kind: 'MINUS',
        value: '-',
        startPos: {line: 1, column: 3},
        endPos: {line: 1, column: 4},
        lineNo: 1,
        colOffset: 3,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '2.5',
        startPos: {line: 1, column: 5},
        endPos: {line: 1, column: 8},
        lineNo: 1,
        colOffset: 5,
      },
      {
        type: 'ENDMARKER',
        kind: 'ENDMARKER',
        value: TOKENS.ENDMARKER,
        startPos: {line: 1, column: 8},
        endPos: {line: 1, column: 8},
        lineNo: 1,
        colOffset: 8,
      },
    ],
  },
  {
    input: '10. + 6 + 12 - 4',
    expected: [
      {
        type: 'ENCODING',
        kind: 'ENCODING',
        value: 'utf-8',
        startPos: {line: 0, column: 0},
        endPos: {line: 0, column: 0},
        colOffset: 0,
        lineNo: 0,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '10.',
        startPos: {line: 1, column: 1},
        endPos: {line: 1, column: 4},
        lineNo: 1,
        colOffset: 1,
      },
      {
        type: 'OP',
        kind: 'PLUS',
        value: '+',
        startPos: {line: 1, column: 5},
        endPos: {line: 1, column: 6},
        lineNo: 1,
        colOffset: 5,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '6',
        startPos: {line: 1, column: 7},
        endPos: {line: 1, column: 8},
        lineNo: 1,
        colOffset: 7,
      },
      {
        type: 'OP',
        kind: 'PLUS',
        value: '+',
        startPos: {line: 1, column: 9},
        endPos: {line: 1, column: 10},
        lineNo: 1,
        colOffset: 9,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '12',
        startPos: {line: 1, column: 11},
        endPos: {line: 1, column: 13},
        lineNo: 1,
        colOffset: 11,
      },
      {
        type: 'OP',
        kind: 'MINUS',
        value: '-',
        startPos: {line: 1, column: 14},
        endPos: {line: 1, column: 15},
        lineNo: 1,
        colOffset: 14,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '4',
        startPos: {line: 1, column: 16},
        endPos: {line: 1, column: 17},
        lineNo: 1,
        colOffset: 16,
      },
      {
        type: 'ENDMARKER',
        kind: 'ENDMARKER',
        value: TOKENS.ENDMARKER,
        startPos: {line: 1, column: 17},
        endPos: {line: 1, column: 17},
        lineNo: 1,
        colOffset: 17,
      },
    ],
  },
  {
    input: '12   * -1000 /      6',
    expected: [
      {
        type: 'ENCODING',
        kind: 'ENCODING',
        value: 'utf-8',
        startPos: {line: 0, column: 0},
        endPos: {line: 0, column: 0},
        colOffset: 0,
        lineNo: 0,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '12',
        startPos: {line: 1, column: 1},
        endPos: {line: 1, column: 3},
        lineNo: 1,
        colOffset: 1,
      },
      {
        type: 'OP',
        kind: 'STAR',
        value: '*',
        startPos: {line: 1, column: 6},
        endPos: {line: 1, column: 7},
        lineNo: 1,
        colOffset: 6,
      },
      {
        type: 'OP',
        kind: 'MINUS',
        value: '-',
        startPos: {line: 1, column: 8},
        endPos: {line: 1, column: 9},
        lineNo: 1,
        colOffset: 8,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '1000',
        startPos: {line: 1, column: 9},
        endPos: {line: 1, column: 13},
        lineNo: 1,
        colOffset: 9,
      },
      {
        type: 'OP',
        kind: 'SLASH',
        value: '/',
        startPos: {line: 1, column: 14},
        endPos: {line: 1, column: 15},
        lineNo: 1,
        colOffset: 14,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '6',
        startPos: {line: 1, column: 21},
        endPos: {line: 1, column: 22},
        lineNo: 1,
        colOffset: 21,
      },
      {
        type: 'ENDMARKER',
        kind: 'ENDMARKER',
        value: TOKENS.ENDMARKER,
        startPos: {line: 1, column: 22},
        endPos: {line: 1, column: 22},
        lineNo: 1,
        colOffset: 22,
      },
    ],
  },
  {
    input: '13.99 // 2',
    expected: [
      {
        type: 'ENCODING',
        kind: 'ENCODING',
        value: 'utf-8',
        startPos: {line: 0, column: 0},
        endPos: {line: 0, column: 0},
        colOffset: 0,
        lineNo: 0,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '13.99',
        startPos: {line: 1, column: 1},
        endPos: {line: 1, column: 6},
        lineNo: 1,
        colOffset: 1,
      },
      {
        type: 'OP',
        kind: 'DOUBLESLASH',
        value: '//',
        startPos: {line: 1, column: 7},
        endPos: {line: 1, column: 9},
        lineNo: 1,
        colOffset: 7,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '2',
        startPos: {line: 1, column: 10},
        endPos: {line: 1, column: 11},
        lineNo: 1,
        colOffset: 10,
      },
      {
        type: 'ENDMARKER',
        kind: 'ENDMARKER',
        value: TOKENS.ENDMARKER,
        startPos: {line: 1, column: 11},
        endPos: {line: 1, column: 11},
        lineNo: 1,
        colOffset: 11,
      },
    ],
  },
  {
    input: '16 ** 4',
    expected: [
      {
        type: 'ENCODING',
        kind: 'ENCODING',
        value: 'utf-8',
        startPos: {line: 0, column: 0},
        endPos: {line: 0, column: 0},
        colOffset: 0,
        lineNo: 0,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '16',
        startPos: {line: 1, column: 1},
        endPos: {line: 1, column: 3},
        lineNo: 1,
        colOffset: 1,
      },
      {
        type: 'OP',
        kind: 'DOUBLESTAR',
        value: '**',
        startPos: {line: 1, column: 4},
        endPos: {line: 1, column: 6},
        lineNo: 1,
        colOffset: 4,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '4',
        startPos: {line: 1, column: 7},
        endPos: {line: 1, column: 8},
        lineNo: 1,
        colOffset: 7,
      },
      {
        type: 'ENDMARKER',
        kind: 'ENDMARKER',
        value: TOKENS.ENDMARKER,
        startPos: {line: 1, column: 8},
        endPos: {line: 1, column: 8},
        lineNo: 1,
        colOffset: 8,
      },
    ],
  },
  {
    input: '12 @ 12',
    expected: [
      {
        type: 'ENCODING',
        kind: 'ENCODING',
        value: 'utf-8',
        startPos: {line: 0, column: 0},
        endPos: {line: 0, column: 0},
        colOffset: 0,
        lineNo: 0,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '12',
        startPos: {line: 1, column: 1},
        endPos: {line: 1, column: 3},
        lineNo: 1,
        colOffset: 1,
      },
      {
        type: 'OP',
        kind: 'AT',
        value: '@',
        startPos: {line: 1, column: 4},
        endPos: {line: 1, column: 5},
        lineNo: 1,
        colOffset: 4,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '12',
        startPos: {line: 1, column: 6},
        endPos: {line: 1, column: 8},
        lineNo: 1,
        colOffset: 6,
      },
      {
        type: 'ENDMARKER',
        kind: 'ENDMARKER',
        value: TOKENS.ENDMARKER,
        startPos: {line: 1, column: 8},
        endPos: {line: 1, column: 8},
        lineNo: 1,
        colOffset: 8,
      },
    ],
  },
  {
    input: '1 < 2',
    expected: [
      {
        type: 'ENCODING',
        kind: 'ENCODING',
        value: 'utf-8',
        startPos: {line: 0, column: 0},
        endPos: {line: 0, column: 0},
        colOffset: 0,
        lineNo: 0,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '1',
        startPos: {line: 1, column: 1},
        endPos: {line: 1, column: 2},
        lineNo: 1,
        colOffset: 1,
      },
      {
        type: 'OP',
        kind: 'LESS',
        value: '<',
        startPos: {line: 1, column: 3},
        endPos: {line: 1, column: 4},
        lineNo: 1,
        colOffset: 3,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '2',
        startPos: {line: 1, column: 5},
        endPos: {line: 1, column: 6},
        lineNo: 1,
        colOffset: 5,
      },
      {
        type: 'ENDMARKER',
        kind: 'ENDMARKER',
        value: TOKENS.ENDMARKER,
        startPos: {line: 1, column: 6},
        endPos: {line: 1, column: 6},
        lineNo: 1,
        colOffset: 6,
      },
    ],
  },
  {
    input: '0x44 << 0x97.fep+809',
    expected: [
      {
        type: 'ENCODING',
        kind: 'ENCODING',
        value: 'utf-8',
        startPos: {line: 0, column: 0},
        endPos: {line: 0, column: 0},
        colOffset: 0,
        lineNo: 0,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '0x44',
        startPos: {line: 1, column: 1},
        endPos: {line: 1, column: 5},
        lineNo: 1,
        colOffset: 1,
      },
      {
        type: 'OP',
        kind: 'LEFTSHIFT',
        value: '<<',
        startPos: {line: 1, column: 6},
        endPos: {line: 1, column: 8},
        lineNo: 1,
        colOffset: 6,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '0x97.fep+809',
        startPos: {line: 1, column: 9},
        endPos: {line: 1, column: 21},
        lineNo: 1,
        colOffset: 9,
      },
      {
        type: 'ENDMARKER',
        kind: 'ENDMARKER',
        value: TOKENS.ENDMARKER,
        startPos: {line: 1, column: 21},
        endPos: {line: 1, column: 21},
        lineNo: 1,
        colOffset: 21,
      },
    ],
  },
  {
    input: 'buffer <<= 0xfff',
    expected: [
      {
        type: 'ENCODING',
        kind: 'ENCODING',
        value: 'utf-8',
        startPos: {line: 0, column: 0},
        endPos: {line: 0, column: 0},
        colOffset: 0,
        lineNo: 0,
      },
      {
        type: 'NAME',
        kind: 'NAME',
        value: 'buffer',
        startPos: {line: 1, column: 1},
        endPos: {line: 1, column: 7},
        lineNo: 1,
        colOffset: 1,
      },
      {
        type: 'OP',
        kind: 'LEFTSHIFTEQUAL',
        value: '<<=',
        startPos: {line: 1, column: 8},
        endPos: {line: 1, column: 11},
        lineNo: 1,
        colOffset: 8,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '0xfff',
        startPos: {line: 1, column: 12},
        endPos: {line: 1, column: 17},
        lineNo: 1,
        colOffset: 12,
      },
      {
        type: 'ENDMARKER',
        kind: 'ENDMARKER',
        value: TOKENS.ENDMARKER,
        startPos: {line: 1, column: 17},
        endPos: {line: 1, column: 17},
        lineNo: 1,
        colOffset: 17,
      },
    ],
  },
  {
    input: 'a = b; a == "c"',
    expected: [
      {
        type: 'ENCODING',
        kind: 'ENCODING',
        value: 'utf-8',
        startPos: {line: 0, column: 0},
        endPos: {line: 0, column: 0},
        colOffset: 0,
        lineNo: 0,
      },
      {
        type: 'NAME',
        kind: 'NAME',
        value: 'a',
        startPos: {line: 1, column: 1},
        endPos: {line: 1, column: 2},
        lineNo: 1,
        colOffset: 1,
      },
      {
        type: 'OP',
        kind: 'EQUAL',
        value: '=',
        startPos: {line: 1, column: 3},
        endPos: {line: 1, column: 4},
        lineNo: 1,
        colOffset: 3,
      },
      {
        type: 'NAME',
        kind: 'NAME',
        value: 'b',
        startPos: {line: 1, column: 5},
        endPos: {line: 1, column: 6},
        lineNo: 1,
        colOffset: 5,
      },
      {
        type: 'SEMI',
        kind: 'SEMI',
        value: ';',
        startPos: {line: 1, column: 6},
        endPos: {line: 1, column: 7},
        lineNo: 1,
        colOffset: 6,
      },
      {
        type: 'NAME',
        kind: 'NAME',
        value: 'a',
        startPos: {line: 1, column: 8},
        endPos: {line: 1, column: 9},
        lineNo: 1,
        colOffset: 8,
      },
      {
        type: 'OP',
        kind: 'EQEQUAL',
        value: '==',
        startPos: {line: 1, column: 10},
        endPos: {line: 1, column: 12},
        lineNo: 1,
        colOffset: 10,
      },
      {
        type: 'STRING',
        kind: 'STRING',
        value: '"c"',
        startPos: {line: 1, column: 13},
        endPos: {line: 1, column: 16},
        lineNo: 1,
        colOffset: 13,
      },
      {
        type: 'ENDMARKER',
        kind: 'ENDMARKER',
        value: TOKENS.ENDMARKER,
        startPos: {line: 1, column: 16},
        endPos: {line: 1, column: 16},
        lineNo: 1,
        colOffset: 16,
      },
    ],
  },
  {
    input: '1 or 2',
    expected: [
      {
        type: 'ENCODING',
        kind: 'ENCODING',
        value: 'utf-8',
        startPos: {line: 0, column: 0},
        endPos: {line: 0, column: 0},
        colOffset: 0,
        lineNo: 0,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '1',
        startPos: {line: 1, column: 1},
        endPos: {line: 1, column: 2},
        lineNo: 1,
        colOffset: 1,
      },
      {
        type: 'OP',
        kind: 'OR',
        value: 'or',
        startPos: {line: 1, column: 3},
        endPos: {line: 1, column: 5},
        lineNo: 1,
        colOffset: 3,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '2',
        startPos: {line: 1, column: 6},
        endPos: {line: 1, column: 7},
        lineNo: 1,
        colOffset: 6,
      },
      {
        type: 'ENDMARKER',
        kind: 'ENDMARKER',
        value: TOKENS.ENDMARKER,
        startPos: {line: 1, column: 7},
        endPos: {line: 1, column: 7},
        lineNo: 1,
        colOffset: 7,
      },
    ],
  },
  {
    input: 'var_one is not var_two',
    expected: [
      {
        type: 'ENCODING',
        kind: 'ENCODING',
        value: 'utf-8',
        startPos: {line: 0, column: 0},
        endPos: {line: 0, column: 0},
        colOffset: 0,
        lineNo: 0,
      },
      {
        type: 'NAME',
        kind: 'NAME',
        value: 'var_one',
        startPos: {line: 1, column: 1},
        endPos: {line: 1, column: 8},
        lineNo: 1,
        colOffset: 1,
      },
      {
        type: 'OP',
        kind: 'IS',
        value: 'is',
        startPos: {line: 1, column: 9},
        endPos: {line: 1, column: 11},
        lineNo: 1,
        colOffset: 9,
      },
      {
        type: 'OP',
        kind: 'NOT',
        value: 'not',
        startPos: {line: 1, column: 12},
        endPos: {line: 1, column: 15},
        lineNo: 1,
        colOffset: 12,
      },
      {
        type: 'NAME',
        kind: 'NAME',
        value: 'var_two',
        startPos: {line: 1, column: 16},
        endPos: {line: 1, column: 23},
        lineNo: 1,
        colOffset: 16,
      },
      {
        type: 'ENDMARKER',
        kind: 'ENDMARKER',
        value: TOKENS.ENDMARKER,
        startPos: {line: 1, column: 23},
        endPos: {line: 1, column: 23},
        lineNo: 1,
        colOffset: 23,
      },
    ],
  },
  {
    input: 'person    in people',
    expected: [
      {
        type: 'ENCODING',
        kind: 'ENCODING',
        value: 'utf-8',
        startPos: {line: 0, column: 0},
        endPos: {line: 0, column: 0},
        colOffset: 0,
        lineNo: 0,
      },
      {
        type: 'NAME',
        kind: 'NAME',
        value: 'person',
        startPos: {line: 1, column: 1},
        endPos: {line: 1, column: 7},
        lineNo: 1,
        colOffset: 1,
      },
      {
        type: 'OP',
        kind: 'IN',
        value: 'in',
        startPos: {line: 1, column: 11},
        endPos: {line: 1, column: 13},
        lineNo: 1,
        colOffset: 11,
      },
      {
        type: 'NAME',
        kind: 'NAME',
        value: 'people',
        startPos: {line: 1, column: 14},
        endPos: {line: 1, column: 20},
        lineNo: 1,
        colOffset: 14,
      },
      {
        type: 'ENDMARKER',
        kind: 'ENDMARKER',
        value: TOKENS.ENDMARKER,
        startPos: {line: 1, column: 20},
        endPos: {line: 1, column: 20},
        lineNo: 1,
        colOffset: 20,
      },
    ],
  },
  {
    input: '12.5 and "hi\\nthere!"',
    expected: [
      {
        type: 'ENCODING',
        kind: 'ENCODING',
        value: 'utf-8',
        startPos: {line: 0, column: 0},
        endPos: {line: 0, column: 0},
        colOffset: 0,
        lineNo: 0,
      },
      {
        type: 'NUMBER',
        kind: 'NUMBER',
        value: '12.5',
        startPos: {line: 1, column: 1},
        endPos: {line: 1, column: 5},
        lineNo: 1,
        colOffset: 1,
      },
      {
        type: 'OP',
        kind: 'AND',
        value: 'and',
        startPos: {line: 1, column: 6},
        endPos: {line: 1, column: 9},
        lineNo: 1,
        colOffset: 6,
      },
      {
        type: 'STRING',
        kind: 'STRING',
        value: '"hi\\nthere!"',
        startPos: {line: 1, column: 10},
        endPos: {line: 1, column: 22},
        lineNo: 1,
        colOffset: 10,
      },
      {
        type: 'ENDMARKER',
        kind: 'ENDMARKER',
        value: TOKENS.ENDMARKER,
        startPos: {line: 1, column: 22},
        endPos: {line: 1, column: 22},
        lineNo: 1,
        colOffset: 22,
      },
    ],
  },
];
